CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128)
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT,
    base_servings INTEGER NOT NULL,
    instructions TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128),
    CONSTRAINT fk_recipes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(64) NOT NULL,
    amount_per_serving DOUBLE PRECISION NOT NULL,
    notes VARCHAR(1024),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128),
    CONSTRAINT fk_recipe_ingredients_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE
);

CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ingredient VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128),
    CONSTRAINT fk_inventory_items_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE menu_plan_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    menu_date DATE NOT NULL,
    meal_name VARCHAR(255) NOT NULL,
    servings INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128),
    CONSTRAINT fk_menu_plan_entries_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_recipes_user ON recipes(user_id);
CREATE INDEX idx_recipe_ingredients_recipe ON recipe_ingredients(recipe_id);
CREATE INDEX idx_inventory_items_user ON inventory_items(user_id);
CREATE INDEX idx_menu_plan_entries_user_date ON menu_plan_entries(user_id, menu_date);
